- hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
  gather_facts: False
  tasks:
    - name: Enable rest API function
      ansible.netcommon.cli_command:
        command: '{{ item }}'
      loop:
        - configure
        - https-server rest access-mode read-write
        - https-server vrf mgmt
        - exit