- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: False
  tasks:
    - name: Create VLAN 410 with description and name
      aoscx_vlan:
        vlan_id: 410
        name: INTERNET_VLAN
        description: This is VLAN 410
- hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
  gather_facts: False
  tasks:
    - name: Execute show vlan on the switch
      aoscx_command:
        commands: ['show vlan']
      register: show_vlan_output

    - name: Output registered variable
      debug:
        var: show_vlan_output